language: c
dist: xenial

addons:
  artifacts:
    paths:
      - artifacts/

# Build on pushes only to given branches
branches:
  only:
    - master
    - 3.10.x
    - 3.12.x

env:
  global:
    - CI_NODE_TOTAL=6
      # Quickest to build, fast performing, debugable builds.
    - CFLAGS="-g1 -O1"
      # upload log files, tarballs etc artifacts from the build.
    - ARTIFACTS_BUCKET=cfengine-travis-artifacts
      # 2 cores according to: https://docs.travis-ci.com/user/ci-environment/
    - MAKEFLAGS=-j3

# Parallel jobs listed here; fastest jobs should come first to give
# feedback ASAP. For more info read this:
# https://docs.travis-ci.com/user/multi-os/
matrix:
  include:
    - os: linux
      env: JOB_TYPE=compile_and_unit_test_asan
    - os: linux
      env: JOB_TYPE=compile_and_unit_test_no_deps COVERAGE=no
    - os: linux
      env: JOB_TYPE=compile_and_unit_test COVERAGE=no
      compiler: clang
    - os: osx
      env: JOB_TYPE=compile_and_unit_test COVERAGE=no
      sudo: false
    - arch: arm64
      os: linux
      env: JOB_TYPE=compile_and_unit_test_asan
    - arch: arm64
      os: linux
      env: JOB_TYPE=compile_and_unit_test_no_deps COVERAGE=no
    - arch: arm64
      dist: focal
      os: linux
      env: JOB_TYPE=compile_and_unit_test COVERAGE=no
      compiler: clang

before_install:
  - if [[ "${TRAVIS_CPU_ARCH}" == "arm64" ]]; then
        sudo apt-get install -y libpcre3 libpcre3-dev;
    fi
  - chmod ug+x ./travis-scripts/*
  - ./travis-scripts/before_install.sh

script: ./travis-scripts/script.sh

after_success: ./travis-scripts/after_success.sh
